name: First Workflow

on:
  - push

jobs: 
  first_job: 
    runs-on: ubuntu-latest
    steps:
      - name: Updated Welcome Message
        run: echo "Welcome to the world of CICD with github actions"

      - name: List all Files including hidden ones
        run: ls -a
      - name: Print Working Directory
        run: pwd
    